### ISSUE TITLE
instructions for acquiring an API token are unclear

### ISSUE THREAD

**Issue by jjb** [shahruz/Send-to-Slack#5]
Hi, thanks for a great project!

I'm not entirely sure what "Grab your API token" means — do I need to make a custom one-off app and then generate a token via the authentication flow from the command line? Or is there a much simpler way to just generate a token?

Thanks, and sorry if I'm missing something obvious.

John

**Comment by ocharles** [comment]
Has this changed again? Now it just says "Generate Test Tokens" at the bottom

**Comment by juztin** [comment]
I just created a token, a few months ago, and can't for the life of me find where to do this now (All I get is the `test token` link as well)  
Why is this so hidden/hard?

**Comment by vning93** [comment]
+1

**Comment by dtnorris** [comment]
+1 VERy confused as to where I'm supposed to generate a "non test" token...

**Comment by rafajaques** [comment]
Hey people!
I had the same issue. Then I tried a "test token" and it seems that this is the only type of token available.
I've used "test token" as a normal token and the authentication and invites worked well.

I hope this helps!

**Comment by aryaman765** [comment]
![image](https://cloud.githubusercontent.com/assets/19321216/16075483/bf69f5c8-330c-11e6-85cd-e3bb9719a5ff.png)

Hey, I am concerned about this warning from Slack.

**Comment by GFoley83** [comment]
Another way I've found that works is to create a bot:
1. https://_**your-team-name**_.slack.com/apps/manage/custom-integrations
2. Click "Bots"
3. Click "Add Configuration"

This will give you an API token that can be disabled, regenerated etc. and you can create as many as you like, for various purposes.

**Comment by agfunder** [comment]
It appears you now have to go to https://my.slack.com/services/new/bot

Completely baffling UI around finding this, and google didnt help either.

**Comment by gac55** [comment]
Thanks to @GFoley83 and @agfunder. However, how did you change the channel the bot posts too?  I don't have the option....
